name: Update README

on:
  schedule:
    # 매일 00:00 UTC에 실행하도록 예약
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        env:
          URL: "https://devyuminkim-devlog.vercel.app"
          CSS_SELECTOR: "#__next > div:nth-child(2) > div > div.notion-frame > div > main > div.notion-page-content > article > div.notion-collection.notion-block-52c3f72df427430ca4768e53c36a61c6 > div:nth-child(2) > div > div"
        run: |
          python blog_posts_scraper.py
          python update_readme.py

      # - name: Clone other GitHub repository
      #   run: |
      #     git clone https://github.com/devYuMinKim/devYuMinKim.git
      #     cp README.md devYuMinKim/README.md

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "<>"

      - name: Update main branch and push the changes
        run: |
          git add README.md
          git diff --cached --quiet || git commit -m "Updated README.md with recent blog posts"
          git remote set-url origin "https://x-access-token:${{ secrets.BLOG_POSTS }}@github.com/devYuMinKim/devYuMinKim.git"
          git push
